---
abstract: 'tools to backup and upgrade WordPress installations'
author:
  - 'Seth Johnson <sj@bluehost.com>'
  - 'Charles McGarvey <cmcgarvey@bluehost.com>'
  - 'Garth Mortensen <gmortensen@bluehost.com>'
build_requires:
  Capture::Tiny: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.008, CPAN::Meta::Converter version 2.150001'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-WordPressTools
no_index:
  directory:
    - t
provides:
  App::WordPressTools:
    file: lib/App/WordPressTools.pm
    version: '1.02'
  wp_tools:
    file: script/wp-tools
    version: '1.02'
recommends:
  IO::Socket::SSL: '1.56'
  Net::SSLeay: '1.49'
requires:
  Digest::MD5: '0'
  Fcntl: '0'
  File::Find: '0'
  File::Path: '0'
  File::Slurper: '0'
  Getopt::Long: '0'
  HTTP::Tiny: '0'
  String::ShellQuote: '0'
  perl: v5.8.1
  sigtrap: '0'
resources:
  bugtracker: https://github.com/bluehost/wp-tools/issues
  repository: git://github.com/bluehost/wp-tools.git
version: '1.02'
x_contributors:
  - 'Charles McGarvey <chazmcgarvey@brokenzipper.com>'
  - 'Gabriel Peery <gabriel.peery@endurance.com>'
  - 'Garth Mortensen <jmort47@hotmail.com>'
  - 'Jason Hall <jayce@lug-nut.com>'
  - 'Mike Hansen <web.mhansen@gmail.com>'
x_serialization_backend: 'YAML::Tiny version 1.69'
